platform :ios, '14.1'
use_frameworks!       # ← без этого podInstall упадёт

target 'iosApp' do
  # подключаем KMM-модуль shared как pod
  pod 'shared', :path => '../shared'
  # и сторонний Pod
  pod 'FirebaseAnalytics'
  pod("lottie-ios")

end